main: thirtyvirus.tmt.TooManyTrees
version: 1.0
name: TooManyTrees
api-version: 1.13

commands:
  tmt:
    description: Main command for TooManyTrees. Use /tmt help for more info
permissions:
  tmt.user:
    description: Allows player to use the plugin's user features
    default: true
  tmt.admin:
    description: Allows player to use the plugin's admin features
    default: op